using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _591RentPractice
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var rentData = new List<Rent>
{
    // 中正區 (10 筆)
    new Rent { Area = "中正區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 15000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 8, Floor = "3樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "熱水器" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "中正區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 12000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡1-5年", BuildingAge = "3年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 6, Floor = "5樓以上", Furniture = "部分家具", Equipment = new List<string> { "洗衣機" }, OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "中正區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 35000, DepositMonths = 2, BuildingType = "公寓", HouseCondition = "屋齡6-10年", BuildingAge = "7年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 25, Floor = "2樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "冰箱", "電視" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "中正區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 18000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡11-15年", BuildingAge = "12年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 10, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string> { "女性專用" } },
    new Rent { Area = "中正區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 10000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡16-20年", BuildingAge = "18年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "地下室", Furniture = "部分家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string>() },
    new Rent { Area = "中正區", RentalType = "整租", RentalCategory = "商業", RentAmount = 45000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "新成屋", BuildingAge = "2年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 30, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "中正區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 22000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "屋齡21年以上", BuildingAge = "25年", Rooms = 1, Halls = 1, Bathrooms = 1, AreaPings = 12, Floor = "頂樓", Furniture = "全套家具", Equipment = new List<string> { "洗衣機", "冰箱" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "中正區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 14000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "4年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 7, Floor = "4樓", Furniture = "部分家具", Equipment = new List<string> { "熱水器", "電視" }, OtherConditions = new List<string>() },
    new Rent { Area = "中正區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 40000, DepositMonths = 2, BuildingType = "透天厝", HouseCondition = "屋齡6-10年", BuildingAge = "8年", Rooms = 3, Halls = 2, Bathrooms = 2, AreaPings = 40, Floor = "1樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "洗衣機", "冰箱" }, OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "中正區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 9000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡11-15年", BuildingAge = "13年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "2樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "近捷運" } },

    // 大安區 (10 筆，高租金區)
    new Rent { Area = "大安區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 25000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 12, Floor = "5樓以上", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "熱水器", "洗衣機" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "大安區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 60000, DepositMonths = 2, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "2年", Rooms = 3, Halls = 2, Bathrooms = 2, AreaPings = 35, Floor = "10樓", Furniture = "全套家具", Equipment = new List<string> { "冰箱", "電視" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "大安區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 20000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "6年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 8, Floor = "3樓", Furniture = "部分家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "女性專用" } },
    new Rent { Area = "大安區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 18000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "14年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 10, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "大安區", RentalType = "整租", RentalCategory = "商業", RentAmount = 80000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "新成屋", BuildingAge = "3年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 50, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "大安區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 30000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "屋齡16-20年", BuildingAge = "17年", Rooms = 1, Halls = 1, Bathrooms = 1, AreaPings = 15, Floor = "頂樓", Furniture = "全套家具", Equipment = new List<string> { "洗衣機", "冰箱" }, OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "大安區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 22000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡21年以上", BuildingAge = "22年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 7, Floor = "4樓", Furniture = "部分家具", Equipment = new List<string> { "電視" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "大安區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 55000, DepositMonths = 2, BuildingType = "透天厝", HouseCondition = "屋齡1-5年", BuildingAge = "5年", Rooms = 2, Halls = 1, Bathrooms = 2, AreaPings = 30, Floor = "2樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "大安區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 16000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "9年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 9, Floor = "地下室", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "大安區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 28000, DepositMonths = 2, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "11年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 13, Floor = "6樓", Furniture = "部分家具", Equipment = new List<string> { "洗衣機" }, OtherConditions = new List<string> { "女性專用" } },

    // 中山區 (5 筆)
    new Rent { Area = "中山區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 32000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 20, Floor = "5樓以上", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "冰箱" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "中山區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 19000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "4年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 10, Floor = "3樓", Furniture = "部分家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "中山區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 15000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "7年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 6, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "中山區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 11000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "12年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "2樓", Furniture = "部分家具", Equipment = new List<string>() , OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "中山區", RentalType = "整租", RentalCategory = "商業", RentAmount = 50000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "屋齡16-20年", BuildingAge = "18年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 25, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string>() },

    // 松山區 (5 筆)
    new Rent { Area = "松山區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 17000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "新成屋", BuildingAge = "2年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 9, Floor = "4樓", Furniture = "全套家具", Equipment = new List<string> { "洗衣機", "電視" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "松山區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 38000, DepositMonths = 2, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "3年", Rooms = 2, Halls = 1, Bathrooms = 2, AreaPings = 28, Floor = "頂樓", Furniture = "全套家具", Equipment = new List<string> { "熱水器", "冰箱" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "松山區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 13000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "8年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 7, Floor = "地下室", Furniture = "部分家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string>() },
    new Rent { Area = "松山區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 9500, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "15年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "1樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "女性專用" } },
    new Rent { Area = "松山區", RentalType = "整租", RentalCategory = "工業", RentAmount = 25000, DepositMonths = 2, BuildingType = "廠房", HouseCondition = "屋齡21年以上", BuildingAge = "30年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 40, Floor = "1樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },

    // 信義區 (5 筆，高檔區)
    new Rent { Area = "信義區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 70000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 3, Halls = 2, Bathrooms = 2, AreaPings = 45, Floor = "15樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "熱水器", "洗衣機", "冰箱", "電視" }, OtherConditions = new List<string> { "近捷運", "有停車位" } },
    new Rent { Area = "信義區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 32000, DepositMonths = 2, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "2年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 14, Floor = "5樓以上", Furniture = "全套家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string>() },
    new Rent { Area = "信義區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 24000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "5年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 9, Floor = "3樓", Furniture = "部分家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "信義區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 20000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "13年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 11, Floor = "2樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "信義區", RentalType = "整租", RentalCategory = "商業", RentAmount = 100000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "新成屋", BuildingAge = "4年", Rooms = 0, Halls = 0, Bathrooms = 2, AreaPings = 60, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "有停車位" } },

    // 大同區 (5 筆)
    new Rent { Area = "大同區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 14000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡16-20年", BuildingAge = "19年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 8, Floor = "1樓", Furniture = "部分家具", Equipment = new List<string> { "洗衣機" }, OtherConditions = new List<string>() },
    new Rent { Area = "大同區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 28000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "屋齡21年以上", BuildingAge = "26年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 22, Floor = "4樓", Furniture = "全套家具", Equipment = new List<string> { "冰箱", "電視" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "大同區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 11000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "地下室", Furniture = "無家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "大同區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 8000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡1-5年", BuildingAge = "3年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "2樓", Furniture = "部分家具", Equipment = new List<string>() , OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "大同區", RentalType = "整租", RentalCategory = "商業", RentAmount = 35000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "屋齡6-10年", BuildingAge = "9年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 20, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string>() },

    // 萬華區 (5 筆，老區，低租金)
    new Rent { Area = "萬華區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 9000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "14年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "3樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },
    new Rent { Area = "萬華區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 13000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡16-20年", BuildingAge = "17年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 7, Floor = "1樓", Furniture = "部分家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "萬華區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 25000, DepositMonths = 2, BuildingType = "透天厝", HouseCondition = "屋齡21年以上", BuildingAge = "35年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 18, Floor = "2樓", Furniture = "全套家具", Equipment = new List<string> { "熱水器", "洗衣機" }, OtherConditions = new List<string>() },
    new Rent { Area = "萬華區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 7000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "新成屋", BuildingAge = "2年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 3, Floor = "頂樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "女性專用" } },
    new Rent { Area = "萬華區", RentalType = "整租", RentalCategory = "商業", RentAmount = 20000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "屋齡1-5年", BuildingAge = "4年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 15, Floor = "1樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },

    // 內湖區 (5 筆，科技園區)
    new Rent { Area = "內湖區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 34000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "6年", Rooms = 2, Halls = 1, Bathrooms = 2, AreaPings = 25, Floor = "5樓以上", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "冰箱", "電視" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "內湖區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 16000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "12年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 9, Floor = "4樓", Furniture = "部分家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "內湖區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 12000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡16-20年", BuildingAge = "18年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 6, Floor = "2樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "內湖區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 10000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡21年以上", BuildingAge = "24年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "1樓", Furniture = "部分家具", Equipment = new List<string>() , OtherConditions = new List<string>() },
    new Rent { Area = "內湖區", RentalType = "整租", RentalCategory = "工業", RentAmount = 30000, DepositMonths = 2, BuildingType = "廠房", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 35, Floor = "1樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "有停車位" } },

    // 南港區 (5 筆)
    new Rent { Area = "南港區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 15000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡1-5年", BuildingAge = "3年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 8, Floor = "3樓", Furniture = "全套家具", Equipment = new List<string> { "洗衣機" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "南港區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 29000, DepositMonths = 2, BuildingType = "公寓", HouseCondition = "屋齡6-10年", BuildingAge = "7年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 20, Floor = "頂樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "南港區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 10500, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡11-15年", BuildingAge = "11年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "地下室", Furniture = "部分家具", Equipment = new List<string> { "冰箱" }, OtherConditions = new List<string>() },
    new Rent { Area = "南港區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 8500, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡16-20年", BuildingAge = "16年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "2樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "南港區", RentalType = "整租", RentalCategory = "商業", RentAmount = 22000, DepositMonths = 2, BuildingType = "店面", HouseCondition = "屋齡21年以上", BuildingAge = "28年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 18, Floor = "1樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },

    // 文山區 (5 筆，住宅區)
    new Rent { Area = "文山區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 26000, DepositMonths = 2, BuildingType = "透天厝", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 3, Halls = 2, Bathrooms = 2, AreaPings = 30, Floor = "1樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "洗衣機", "電視" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "文山區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 14000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "5年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 7, Floor = "4樓", Furniture = "部分家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "文山區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 10000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡6-10年", BuildingAge = "8年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "1樓", Furniture = "無家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "文山區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 7500, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡11-15年", BuildingAge = "13年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 3, Floor = "2樓", Furniture = "部分家具", Equipment = new List<string>() , OtherConditions = new List<string>() },
    new Rent { Area = "文山區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 22000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "屋齡16-20年", BuildingAge = "19年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 16, Floor = "3樓", Furniture = "全套家具", Equipment = new List<string> { "冰箱" }, OtherConditions = new List<string> { "可養寵物" } },

    // 北投區 (5 筆，郊區)
    new Rent { Area = "北投區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 12000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡21年以上", BuildingAge = "32年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 6, Floor = "地下室", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },
    new Rent { Area = "北投區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 20000, DepositMonths = 2, BuildingType = "透天厝", HouseCondition = "新成屋", BuildingAge = "2年", Rooms = 2, Halls = 1, Bathrooms = 1, AreaPings = 15, Floor = "1樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "熱水器" }, OtherConditions = new List<string> { "有停車位" } },
    new Rent { Area = "北投區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 8000, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "屋齡1-5年", BuildingAge = "4年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "頂樓", Furniture = "部分家具", Equipment = new List<string> { "洗衣機" }, OtherConditions = new List<string>() },
    new Rent { Area = "北投區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 6000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡6-10年", BuildingAge = "9年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 3, Floor = "5樓以上", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "北投區", RentalType = "整租", RentalCategory = "農地", RentAmount = 15000, DepositMonths = 1, BuildingType = "農舍", HouseCondition = "屋齡11-15年", BuildingAge = "12年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 50, Floor = "1樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },

    // 士林區 (5 筆)
    new Rent { Area = "士林區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 24000, DepositMonths = 2, BuildingType = "大樓", HouseCondition = "屋齡16-20年", BuildingAge = "17年", Rooms = 2, Halls = 1, Bathrooms = 2, AreaPings = 18, Floor = "4樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣", "冰箱", "電視" }, OtherConditions = new List<string> { "可養寵物" } },
    new Rent { Area = "士林區", RentalType = "套房", RentalCategory = "住宅", RentAmount = 11000, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡21年以上", BuildingAge = "25年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 5, Floor = "2樓", Furniture = "部分家具", Equipment = new List<string> { "熱水器" }, OtherConditions = new List<string>() },
    new Rent { Area = "士林區", RentalType = "雅房", RentalCategory = "住宅", RentAmount = 8500, DepositMonths = 1, BuildingType = "大樓", HouseCondition = "新成屋", BuildingAge = "1年", Rooms = 0, Halls = 0, Bathrooms = 1, AreaPings = 4, Floor = "1樓", Furniture = "全套家具", Equipment = new List<string> { "冷氣" }, OtherConditions = new List<string> { "近捷運" } },
    new Rent { Area = "士林區", RentalType = "分租", RentalCategory = "住宅", RentAmount = 5500, DepositMonths = 1, BuildingType = "公寓", HouseCondition = "屋齡1-5年", BuildingAge = "3年", Rooms = 1, Halls = 0, Bathrooms = 1, AreaPings = 3, Floor = "3樓", Furniture = "無家具", Equipment = new List<string>() , OtherConditions = new List<string>() },
    new Rent { Area = "士林區", RentalType = "整租", RentalCategory = "住宅", RentAmount = 18000, DepositMonths = 2, BuildingType = "透天厝", HouseCondition = "屋齡6-10年", BuildingAge = "10年", Rooms = 3, Halls = 1, Bathrooms = 1, AreaPings = 12, Floor = "1樓", Furniture = "部分家具", Equipment = new List<string> { "洗衣機" }, OtherConditions = new List<string> { "有停車位" } }
};
        }
    }
}
